# Generated by Django 6.0.5 on 2026-05-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start_date', models.DateField(blank=True, null=True)),
                ('season_end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TOTAL', 'Total'), ('HOME', 'Home'), ('AWAY', 'Away')], default='TOTAL', max_length=10)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.competition')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'ordering': ['competition', 'type'],
                'unique_together': {('competition', 'type', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('played_games', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('draw', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('goals_for', models.PositiveSmallIntegerField(default=0)),
                ('goals_against', models.PositiveSmallIntegerField(default=0)),
                ('goal_difference', models.SmallIntegerField(default=0)),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='standings.standing')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_entries', to='teams.team')),
            ],
            options={
                'verbose_name': 'Table Entry',
                'verbose_name_plural': 'Table Entries',
                'ordering': ['standing', 'position'],
                'unique_together': {('standing', 'team')},
            },
        ),
    ]
