# Generated by Django 6.0.5 on 2026-05-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('area_name', models.CharField(blank=True, max_length=100)),
                ('area_code', models.CharField(blank=True, max_length=5)),
                ('emblem_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('utc_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('SUSPENDED', 'Suspended'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('AWARDED', 'Awarded')], db_index=True, max_length=20)),
                ('matchday', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('score_home_ft', models.SmallIntegerField(blank=True, null=True)),
                ('score_away_ft', models.SmallIntegerField(blank=True, null=True)),
                ('score_home_ht', models.SmallIntegerField(blank=True, null=True)),
                ('score_away_ht', models.SmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.competition')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-utc_date'],
                'indexes': [models.Index(fields=['competition', 'matchday'], name='matches_mat_competi_68980f_idx'), models.Index(fields=['competition', 'status'], name='matches_mat_competi_a94d27_idx')],
            },
        ),
    ]
