# Generated by Django 6.0.5 on 2026-05-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('tla', models.CharField(blank=True, max_length=5)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crest_url', models.URLField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('area_name', models.CharField(blank=True, max_length=100)),
                ('area_code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Defence', 'Defence'), ('Midfield', 'Midfield'), ('Offence', 'Offence')], max_length=20)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['team', 'shirt_number', 'name'],
            },
        ),
    ]
